name: Generate CV

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
      
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: '2.3'
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Generate CV
        run: |
            for file in cv-*.yaml; do
              locale="$(grep -Po '(?<=cv-)[-_a-z]{2}(?=\.yaml)' <<< "$file")"

              uv run rendercv render "$file" --output-folder-name "build/${locale}/"
            done