name: Release new CV version

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  GITHUB_REPOSITORY_URL: "https://${{ github.server_url }}/${{ github.repository }}"

jobs:
  generate-cv:
    uses: ./.github/workflows/generate-cv.yml

  create-release:
    runs-on: ubuntu-latest
    needs: [generate-cv]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Download CV artifacts
        uses: actions/download-artifact@v8
        with:
          name: generated-cv
          path: build/lang/

      - name: Rename CV files for release
        run: |
          mkdir -p build/release/
          for file in build/lang/**/*.pdf; do
            filename="$(basename "$file")"
            lang="$(basename "$(dirname "$file")")"
            new_filename="${filename%.pdf}-${lang}.pdf"

            cp "$file" "build/release/${new_filename}"
          done

      - name: Generate version tag
        id: version
        shell: bash
        run: |
          cv_date=$(date +'%Y.%m.%d')
          cv_time=$(date +'%H.%M.%S')
          cv_version="cv-${cv_date}-${cv_time}"

          echo "CV_DATE=$cv_date" >> $GITHUB_OUTPUT
          echo "CV_TIME=$cv_time" >> $GITHUB_OUTPUT
          echo "CV_VERSION=$cv_version" >> $GITHUB_OUTPUT

          (
            delimiter="$(tr -dc A-Za-z0-9 </dev/urandom 2>/dev/null | head -c 64)" || true
            echo "GENERATED_FILES_TABLE<<${delimiter}"
            echo "| Language | File Name |"
            echo "|----------|-----------|"
            for file in build/release/*.pdf; do
              filename="$(basename "$file")"
              lang="${filename##*-}"
              lang="${lang%.pdf}"

              download_base_url="${{ env.GITHUB_REPOSITORY_URL }}/releases/download/$cv_version"
              echo "| ${lang} | [${filename}](${download_base_url}/${filename}) |"
            done
            echo "$delimiter"
          ) >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.version.outputs.CV_VERSION }}
          name: CV Version ${{ steps.version.outputs.CV_VERSION }}
          body: |
            # `${{ steps.version.outputs.CV_VERSION }}`

            This is an automated release of the CV generated from the latest commit on the main branch.

            ## Generated files

            ${{ steps.version.outputs.GENERATED_FILES_TABLE }}

            <sub>
              <a href="${{ env.GITHUB_REPOSITORY_URL }}/releases/latest">
                Go to latest CV release
              </a>
            </sub>
          make_latest: true
          fail_on_unmatched_files: true
          files: |
            build/release/*.pdf

      - name: Add summary message
        run: |
          cat <<-EOF >> $GITHUB_STEP_SUMMARY
          # New CV Release Created
          A new CV version has been released: **${{ steps.version.outputs.CV_VERSION }}**

          You can download the generated CV files from the [Releases](${{ env.GITHUB_REPOSITORY_URL }}/releases/tag/${{ steps.version.outputs.CV_VERSION }})

          ## Generated files

          ${{ steps.version.outputs.GENERATED_FILES_TABLE }}
  gh-pages:
    runs-on: ubuntu-latest
    needs: [generate-cv]

    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Download CV artifacts
        uses: actions/download-artifact@v8
        with:
          name: generated-cv
          path: build/lang/

      - name: Prepare HTML files for deployment
        run: |
          mkdir -p build/release/
          for file in build/lang/**/*.html; do
            filename="$(basename "$file")"
            lang="$(basename "$(dirname "$file")")"

            mkdir -p "build/release/${lang}"
            cp "$file" "build/release/${lang}/index.html"
          done

          cat <<-EOF > build/release/index.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Curriculum Vitae</title>
          </head>
          <body>
            <h1>Curriculum Vitae</h1>
            <ul id="language-list">
              $(for dir in build/release/*/; do
                  lang="$(basename "$dir")"
                  echo "<li class='language'><a href=\"${lang}/\">${lang}</a></li>"
                done)
            </ul>
          </body>
          </html>
          EOF

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Upload artifacts for Github Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: build/release

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
