name: Release new CV version

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-cv:
    uses: ./.github/workflows/generate-cv.yml
    
  release:
    runs-on: ubuntu-latest
    needs: [generate-cv]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Download CV artifacts
        uses: actions/download-artifact@v5
        with:
          name: generated-cv
          path: build/lang/

      - name: Rename CV files for release
        run: |
          mkdir -p build/release/
          for file in build/lang/**/*.pdf; do
            filename="$(basename "$file")"
            lang="$(basename "$(dirname "$file")")"
            new_filename="${filename%.pdf}-${lang}.pdf"

            cp "$file" "build/release/${new_filename}"
          done

      - name: Generate version tag
        id: version
        run: |
          echo "CV_VERSION=cv-$(date +'%Y.%m.%d-%H.%M.%S')" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.CV_VERSION }}
          name: CV Version ${{ steps.version.outputs.CV_VERSION }}
          body: "Automated release of CV version ${{ steps.version.outputs.CV_VERSION }}"
          make_latest: true
          fail_on_unmatched_files: true
          files: |
            build/release/*.pdf
      
      - name: Add summary message
        run: |
          cat <<-EOF >> $GITHUB_STEP_SUMMARY
          # New CV Release Created
          A new CV version has been released: **${{ steps.version.outputs.CV_VERSION }}**

          You can download the generated CV files from the [Releases](https://github.com/${{ github.repository }}/releases/tag/${{ steps.version.outputs.CV_VERSION }})
          
          ## Generated CV Files
          | Language | File Name |
          |----------|-----------|
          $(for file in build/release/*.pdf; do
              filename="$(basename "$file")"
              lang="${filename##*-}"
              lang="${lang%.pdf}"
              echo "| ${lang} | ${filename} |"
            done)
          EOF